spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/kino"
    username: "postgres"
    password: "1111"
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect

server:
  port: 8187

logging:
  level:
    org:
      hibernate:
        sql: debug